base_urls:
  amazon: "https://www.amazon.in"
  api: "https://dummyjson.com"

browser:
  name: "chrome"
  headless: false
  timeout: 10
  implicit_wait: 5

test_data:
  excel_path: "data/users.xlsx"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

reports:
  path: "reports/"
  allure_results: "reports/allure-results"
